name: Deploy to TransIP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: royabb.ssh.transip.me
        username: royabbinkcom
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Ga naar de website directory
          cd www/
          
          # Maak v3 directory als het niet bestaat
          mkdir -p v3
          cd v3
          
          # Clone of update repository
          if [ -d ".git" ]; then
            git pull origin main
          else
            git clone https://github.com/roy-abbink/website.git .
          fi
          
          # Set juiste permissies
          chmod -R 755 .